services:
  postgres:
    image: postgres:latest
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
